import RedirectNavbar from "@/app/components/RedirectNavbar";
import { Metadata } from "next";
import { ErrorRes, inventoryInOutType } from "@/app/types/inven-inout-type";
import InventoryGraph from "./InventoryGraph";
import { Card } from "@/components/ui/card";
import NumberCard from "./NumberCard";
import { fetchInventoryCurrentDate } from "@/app/lib/helpers/fetchData";

type Props = {
  searchParams: {
    startdate: string;
    enddate: string;
    plant: string;
  };
};

export const metadata: Metadata = {
  title: "Inventory In/Out",
  description: "Generated by create next app",
};

const page = async ({ searchParams }: Props) => {
  const { startdate, enddate, plant } = searchParams;

  return (
    <div>
      <RedirectNavbar
        url="/inventory-inout"
        startdate={new Date(startdate)}
        enddate={new Date(enddate)}
        plant={plant}
      />

      <section className="grid grid-cols-4 grid-rows-2 gap-5 m-5 h-[calc(100vh-120px)]">
        <Card className="col-span-3 row-span-2 p-2 shadow-md border-0 rounded-md  bg-white bg-opacity-5 backdrop-blur-md">
          <InventoryGraph />
        </Card>
        <NumberCard />
      </section>
    </div>
  );
};

export default page;
